### PR TITLE
fix: use afterRender and host

### LINKED ISSUE #513: Warning when deleting a split area.
Describe the bug:
When deleting a split area, the following warning appears in the console:
as-split: Percent areas must total 100%
After reviewing my implementation, I confirmed that the area sizes are set correctly.
In my use case, I always have at least 1 and at most 2 split areas at any given time.
- When starting with one area or adding a second area, everything works as expected, and no warnings appear.
- However, when deleting one of the areas, the warning is triggered—even though the remaining area is configured correctly.

Library version:
@angular-split version: "^19.0.0",
angular: 19 (latest).

Steps to reproduce the issue:

I created a demo to reproduce the issue:
[Remove area demo](https://stackblitz.com/edit/stackblitz-starters-d4fqgbco?file=src%2Fapp%2Fmy-splitter%2Fmy-splitter.component.ts)

1. Start with 2 split area.
2. Delete one of the areas programmatically(by button click).

Observe the warning in the console:
`as-split: Percent areas must total 100%`

Expected behavior:
Deleting a split area should not result in a warning.

### PR DESCRIPTION
**Pull request by SanderElias**
@Harpush  @Jefiozie 
I moved the effect to afterrendereffect, and moved the other effect into 'host' 

With this change, we no longer need to use `renderer2` in the component.  Also, AFAIK, there is no change in the CD of the parent component.  Using the computed value ensures that the thing is debounced as accurately as possible.

I'm not 100% sure about this thing tho, so please review carefully

should closes #513

### CODE REVIEW

**Comment by SanderElias** [comment]
BTW, I have no idea why the linter now forced me to remove the `;` in [split-transitions.component.ts](https://github.com/angular-split/angular-split/pull/514/commits/529fa50481f018a445e813e6977456f9a72fa7c2#diff-8e447e85e3e9883b99d24a2cdf838be1a7a3611e11ab4d8f6e421d3070e489c8)

However, it was a stray, unneeded `;`, so that comes as a drive-by fix.

File: projects/angular-split/src/lib/split/split.component.ts [hunk 1]
```diff
@@ -164,24 +165,18 @@ export class SplitComponent {
   constructor() {
     if (isDevMode()) {
       // Logs warnings to console when the provided areas sizes are invalid
-      effect(() => {
-        // Special mode when no size input was declared which is a valid mode
-        if (this.unit() === 'percent' && this._visibleAreas().every((area) => area.size() === 'auto')) {
-          return
-        }
+      afterRenderEffect({
```
Comment (Harpush) [inline projects/angular-split/src/lib/split/split.component.ts:168]: I think we need a note comment here. I think effect is more correct here than afterRenderEffect but we are forced to use it until angular fixes https://github.com/angular/angular/issues/59067.
Or do you think this is the preferred solution even after the issue is fixed?

Comment (SanderElias) [reply projects/angular-split/src/lib/split/split.component.ts:168]: I think it is indeed the preferred solution. 
Let me explain. The `afterRender({read: () => ...})` runs when all Angular processing is done.  The code we run is _not_ going to change anything Angular should care about, so it is the correct abstraction

File: projects/angular-split/src/lib/split/split.component.ts [hunk 2]
```diff
@@ -85,10 +84,12 @@ export const SPLIT_AREA_CONTRACT = new InjectionToken<SplitAreaComponent>('Split
   templateUrl: './split.component.html',
   styleUrl: './split.component.css',
   changeDetection: ChangeDetectionStrategy.OnPush,
+  // host: {
```
Comment (Harpush) [inline projects/angular-split/src/lib/split/split.component.ts:87]: Forgotten comment

File: projects/angular-split/src/lib/split/split.component.ts [hunk 3]
```diff
@@ -164,22 +165,25 @@ export class SplitComponent {
...
-    // is updated on every mouse move. Doing it this way will prevent change detection cycles in parent.
-    effect(() => {
-      const gridTemplateColumnsStyle = this.gridTemplateColumnsStyle()
-      this.renderer.setStyle(this.elementRef.nativeElement, 'grid-template', gridTemplateColumnsStyle)
+    // we are running this after Angular has completed its CD loop
+    // as we are updating the style of the host, and we don't want to re-trigger the CD loop
+    // doing this in the host of the component would retrigger the CD too many times
+    afterRenderEffect({
+      read: () => {
+        this.elementRef.nativeElement.style.gridTemplate = this.gridTemplateColumnsStyle()
```
Comment (Harpush) [inline projects/angular-split/src/lib/split/split.component.ts:185]: Isn't `Rendered2` the preferred way when doing direct DOM operations?

File: projects/angular-split/src/lib/split/split.component.ts [hunk 4]
```diff
@@ -164,22 +165,25 @@ export class SplitComponent {
...
       })
     }
 
-    // Responsible for updating grid template style. Must be this way and not based on HostBinding
-    // as change detection for host binding is bound to the parent component and this style
-    // is updated on every mouse move. Doing it this way will prevent change detection cycles in parent.
-    effect(() => {
-      const gridTemplateColumnsStyle = this.gridTemplateColumnsStyle()
-      this.renderer.setStyle(this.elementRef.nativeElement, 'grid-template', gridTemplateColumnsStyle)
+    // we are running this after Angular has completed its CD loop
```
Comment (Harpush) [inline projects/angular-split/src/lib/split/split.component.ts:180]: Add some more context why read phase is preferred here

File: projects/angular-split/src/lib/split/split.component.ts (hunk 3 above)
Comment (SanderElias) [reply projects/angular-split/src/lib/split/split.component.ts:188]: Not anymore.

**Review by Harpush — APPROVED** [review]
LGTM
